github:
  description: A full-featured license tool to check and fix license headers and resolve dependencies' licenses.
  homepage: https://skywalking.apache.org/
  labels:
    - cli
    - tools
    - license
    - licensing
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false
  protected_branches:
    main:
      required_status_checks:
        strict: true
        contexts:
          - Build LicenseEye
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
