# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: fmt
              desc: logging is allowed only by logutils.Log
    dupl:
      threshold: 200
    funlen:
      lines: 200
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - ifElseChain
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - shadow
    lll:
      line-length: 150
    misspell:
      locale: US
      ignore-rules:
        - analogue
        - analyse
        - artefact
        - authorised
        - calibre
        - cancelled
        - catalogue
        - categorise
        - centre
        - emphasised
        - favour
        - favourite
        - fulfil
        - fulfilment
        - initialise
        - labelling
        - labour
        - licence
        - maximise
        - modelled
        - modelling
        - offence
        - optimise
        - organisation
        - organise
        - practise
        - programme
        - realise
        - recognise
        - signalling
        - utilisation
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - funlen
        path: _test\.go
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/apache/skywalking-eyes
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
