header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - '**/*.md'
    - '**/*.json'
    - '**/*.txt'
    - '.gitignore'
    - '.gitmodules'
    - 'LICENSE'
    - 'NOTICE'
    - 'go.mod'
    - 'go.sum'

  comment: on-failure
