name: publish-docker

on:
  push:
    branches:
      - main

env:
  HUB: ghcr.io/apache/skywalking-eyes

jobs:
  build:
    if: github.repository == 'apache/skywalking-eyes'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30
    env:
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
          make docker && make docker-push
          docker tag $HUB/license-eye:$VERSION $HUB/license-eye:latest
          docker push $HUB/license-eye:latest
